# Generated by Django 5.0.3 on 2024-04-25 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_favoritebooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_url",
        ),
    ]
