# Generated by Django 5.0.3 on 2024-04-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_book_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(null=True),
        ),
    ]
