name: Deploy Frontend
on:
    push:
        branches:
            - main  
    workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: favbooks   
  AZURE_WEBAPP_PACKAGE_PATH: './frontend'      
  NODE_VERSION: '20'
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                sparse-checkout: |
                    .github
                    frontend

            - name: Set up Node.js
              
              uses:  actions/setup-node@v3
              with:
                node-version: ${{ env.NODE_VERSION }}
            - name: Install dependencies and build
              working-directory: ./frontend
              run: |
                npm install
                npm run build --if-present
            
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                name: node-app
                path: dist
                if-no-files-found: error
    
    deploy:
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        runs-on: ubuntu-latest
        needs: build
        environment:
          name: 'production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                name: node-app
            
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                slot-name: 'production'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}